version: '3'
services:
  pismo:
    container_name: pismo_app
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/pismo/
    depends_on:
      - postgres
    networks:
      - pismo


  postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=pismo 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pismo_api
      - DATABASE_HOST=postgres
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - pismo
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pismo.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - pismo
    restart: unless-stopped

volumes:
    api:
    database_postgres:                  
    
networks:
    pismo:
        driver: bridge