// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Account struct {
	ID             int32     `json:"id"`
	Balance        float64   `json:"balance"`
	DocumentNumber string    `json:"document_number"`
	CreatedAt      time.Time `json:"created_at"`
}

type Transaction struct {
	ID              int32     `json:"id"`
	AccountID       int32     `json:"account_id"`
	TransactionType string    `json:"transaction_type"`
	Amount          float64   `json:"amount"`
	EventDate       time.Time `json:"event_date"`
}
